---

services:
  nestapp:
    image: ${COMPOSE_PROJECT_NAME}:latest
    container_name: fastapi-rest-tpl
    working_dir: /app/src
    command: /bin/ash -ci "poetry run uvicorn main:app --reload --host 0.0.0.0 --port 3000"
    restart: unless-stopped
    platform: ${PLATFORM}
    tty: true
    ports:
      - 3000:3000
    environment:
      - ENVIRONMENT=development
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
    depends_on:
      - ms-db
    volumes:
      - ../:/app:rw
      - backend-packages:/app/.venv:rw

volumes:
  backend-packages:
    name: ${COMPOSE_PROJECT_NAME}-packages
    external: true
