---

services:
  nestapp:
    container_name: nestjs-gql-tpl
    restart: unless-stopped
    environment:
      - HTTP_PORT=4000
      - INTEGRATION_ENVIRONMENT_URL_LIVENESS=
      - INTEGRATION_API_TOKEN=
      - UNLEASH_API_URL=
      - UNLEASH_API_TOKEN=
    ports:
      - "3000:4000"
    depends_on:
      - unleash
    networks:
      - app-network

networks:
  app-network:
