---
version: '3.8'

services:
  nestapp:
    image: ms-nestjs-template:1.0.0
    container_name: api_nestjs_template
    restart: unless-stopped

  unleash:
    image: unleashorg/unleash-server
    container_name: unleash-server
    restart: unless-stopped
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=unleash
      - DATABASE_USERNAME=unleash_user
      - DATABASE_PASSWORD=some_password
      - DATABASE_SSL=false
    ports:
      - "4242:4242"
    depends_on:
      - postgres
    networks:
      app-network:
  
  postgres:
    image: postgres
    container_name: unleash_database
    environment:
      - POSTGRES_PASSWORD=some_password
      - POSTGRES_USER=unleash_user
      - POSTGRES_DB=unleash
    networks:
      app-network:

networks:
  app-network:
