---
version: '3.8'

services:
  nestapp:
    image: ms-nestjs-template:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev

  unleash:
    image: unleashorg/unleash-server
    container_name: unleash-server
    restart: unless-stopped
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=unleash
      - DATABASE_USERNAME=unleash_user
      - DATABASE_PASSWORD=some_password
      - DATABASE_SSL=false
    ports:
      - "4242:4242"
    depends_on:
      - postgres
    networks:
      app-network:
  
  postgres:
    image: postgres
    container_name: unleash_database
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      - POSTGRES_PASSWORD=some_password
      - POSTGRES_USER=unleash_user
      - POSTGRES_DB=unleash
    volumes:
      - 'app_db:/var/lib/postgresql/data'
    networks:
      app-network:

networks:
  app-network:

volumes:
  app_db: null
