name: ${COMPOSE_PROJECT_NAME}

services:
  webapp:
    container_name: ${COMPOSE_PROJECT_NAME}-webapp
    image: ${COMPOSE_PROJECT_NAME}-webapp-dev:latest
    ports:
      - 8080:3000
    working_dir: /app
    command: /bin/ash -ci "npm run dev"
    platform: ${PLATFORM}
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
    environment:
      - NODE_ENV=development
      - REACT_APP_BASE_PATH=http://localhost:5002/v1/
      - REACT_APP_VERSION=1.2.6
      - REACT_APP_API_KEY=
      - REACT_APP_AUTH_DOMAIN=
      - REACT_APP_DATABASE_URL=
      - REACT_APP_PROJECT_ID=
      - REACT_APP_STORAGE_BUCKET=
      - REACT_APP_MESSAGING_SENDER_ID=
      - REACT_APP_FIREBASE_APP_ID=
      - REACT_APP_MEASUREMENT_ID=
    tty: true
    links:
      - api
    volumes:
      - ../ms-conference-webapp/:/app:rw
      - frontend-packages:/app/node_modules

  storybook:
    container_name: ${COMPOSE_PROJECT_NAME}-webapp-storybook
    image: ${COMPOSE_PROJECT_NAME}-webapp-dev:latest
    ports:
      - 6006:6006
    working_dir: /app
    command: /bin/ash -ci "npm run storybook"
    platform: ${PLATFORM}
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    tty: true
    volumes:
      - ../ms-conference-webapp/:/app:rw
      - frontend-packages:/app/node_modules

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-api-network

volumes:
  frontend-packages:
    name: ${COMPOSE_PROJECT_NAME}-webapp-packages
    external: true
