---

services:
  admin:
    image: ${COMPOSE_PROJECT_NAME}-admin:latest
    container_name: ${COMPOSE_PROJECT_NAME}-admin:latest
    working_dir: /app/src
    command: /bin/ash -ci "pipenv run uvicorn main:app --reload --host 0.0.0.0 --port 3000"
    restart: unless-stopped
    platform: ${PLATFORM}
    tty: true
    ports:
      - 3000:3000
    environment:
      - ENVIRONMENT=development
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
    volumes:
      - ../:/app:rw
      - backend-packages:/app/.venv:rw

volumes:
  backend-packages:
    name: ${COMPOSE_PROJECT_NAME}-admin-packages
    external: true
