---

services:
  # observability-prometheus:
  ob-prometheus:
    container_name: ${COMPOSE_PROJECT_NAME}-ob-prometheus
    image: prom/prometheus
    platform: ${PLATFORM}
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ../tools/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-network

volumes:
  prometheus-data:
    name: ${COMPOSE_PROJECT_NAME}-prometheus-data
