---

services:
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: mongo:6.0.6
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DEFAULT_DB}
    volumes:
      - dev-db:/data/db
      - ../scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-network

volumes:
  dev-db:
    name: ${COMPOSE_PROJECT_NAME}-dev-db
  backend-packages:
    name: ${COMPOSE_PROJECT_NAME}-backend-packages
    external: true
