---

services:
  ms-db:
    image: postgres:13-alpine
    container_name: ms-db
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      - POSTGRES_PASSWORD=some_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - 'ms_db:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready - U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  ms_db: null
