# name: Build and Deploy to Azure

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'backend/project/src/**'
#       - 'backend/project/Dockerfile'
#       - 'backend/project/*.js'
#       - 'backend/project/*.json'

# jobs:
#   build_and_deploy:
#     permissions:
#       id-token: write
#       contents: read
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       # Login to Azure
#       - name: Login to Azure
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#       # Build Docker image using Yarn
#       - name: Build Docker image
#         run: |
#           cd backend
#           docker build -t containerregistry.azurecr.io/ms-backend-bff:${{ github.sha }} .

#       # Login to Azure Container Registry
#       - name: Login to Azure Container Registry
#         uses: azure/docker-login@v1
#         with:
#           login-server: containerregistry.azurecr.io
#           username: ${{ secrets.AZURE_ACR_USERNAME }}
#           password: ${{ secrets.AZURE_ACR_PASSWORD }}

#       # Push the image to Azure Container Registry
#       - name: Push image to ACR
#         run: |
#           docker tag containerregistry.azurecr.io/ms-backend-bff:${{ github.sha }} containerregistry.azurecr.io/ms-backend-bff:latest
#           docker push containerregistry.azurecr.io/ms-backend-bff:latest

#       # Optional: Logout of Azure
#       - name: Logout of Azure
#         run: az logout
