name: Pull Request Verification Workflow for backend templates

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**

permissions:
  contents: read

env:
  PLATFORM: linux/amd64

jobs:
  get-changed-packages:
    name: Get list of changed packages
    runs-on: ubuntu-24.04
    outputs:
      changed_packages: ${{ steps.changed-packages.outputs.changed_packages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: changed-packages
        uses: ./.github/actions/get-changed-packages

      - name: Output changed packages
        run: |
          echo "Changed packages: ${{ steps.changed-packages.outputs.changed_packages }}"
          echo ""
          echo "Summary: ${{ steps.changed-packages.outputs.summary }}"

  nestjs-rest-tpl-unit-tests:
    name: running lint and unit tests for nestjs rest template
    needs: get-changed-packages
    if: ${{ contains(needs.get-changed-packages.outputs.changed_packages, 'tpl-nestjs-rest') }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./backend/nestjs-rest-tpl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build container for development
        run: make build-dev

      - name: Install dependencies
        run: make install-dependencies

      - name: Run Linting
        run: make lint

      - name: Run Unit Tests
        run: make unit-tests

      - name: Build container for production
        run: make build-prod

  nestjs-gql-tpl-unit-tests:
    name: running lint and unit tests for nestjs graphql template
    needs: get-changed-packages
    if: ${{ contains(needs.get-changed-packages.outputs.changed_packages, 'tpl-nestjs-gql') }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./backend/nestjs-gql-tpl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build container for development
        run: make build-dev

      - name: Install dependencies
        run: make install-dependencies

      - name: Run Linting
        run: make lint

      - name: Run Unit Tests
        run: make unit-tests

      - name: Build container for production
        run: make build-prod

  fastapi-rest-tpl-unit-tests:
    name: running lint and unit tests for fastapi rest template
    needs: get-changed-packages
    if: ${{ contains(needs.get-changed-packages.outputs.changed_packages, 'tpl-fastapi-rest') }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./backend/fastapi-rest-tpl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build container for development
        run: make build-dev

      - name: Install dependencies
        run: make install-dependencies

      - name: Run Linting
        run: make lint

      - name: Run Unit Tests
        run: make run-tests

      - name: Build container for production
        run: make build-prod
